/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin.stats'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin.paiements'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminDemandesRouteImport } from './routes/_authenticated/admin.demandes'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminDemandesIndexRouteImport } from './routes/_authenticated/admin.demandes.index'
import { Route as AuthenticatedAdminDemandesIdRouteImport } from './routes/_authenticated/admin.demandes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/paiements',
    path: '/paiements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDemandesRoute =
  AuthenticatedAdminDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDemandesIndexRoute =
  AuthenticatedAdminDemandesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminDemandesRoute,
  } as any)
const AuthenticatedAdminDemandesIdRoute =
  AuthenticatedAdminDemandesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminDemandesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/demandes/$id': typeof AuthenticatedAdminDemandesIdRoute
  '/admin/demandes/': typeof AuthenticatedAdminDemandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/demandes/$id': typeof AuthenticatedAdminDemandesIdRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/demandes': typeof AuthenticatedAdminDemandesRouteWithChildren
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/demandes/$id': typeof AuthenticatedAdminDemandesIdRoute
  '/_authenticated/admin/demandes/': typeof AuthenticatedAdminDemandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/clients'
    | '/admin/demandes'
    | '/admin/logs'
    | '/admin/paiements'
    | '/admin/stats'
    | '/admin/'
    | '/admin/demandes/$id'
    | '/admin/demandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/clients'
    | '/admin/logs'
    | '/admin/paiements'
    | '/admin/stats'
    | '/admin'
    | '/admin/demandes/$id'
    | '/admin/demandes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/demandes'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/demandes/$id'
    | '/_authenticated/admin/demandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demandes': {
      id: '/_authenticated/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AuthenticatedAdminDemandesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demandes/': {
      id: '/_authenticated/admin/demandes/'
      path: '/'
      fullPath: '/admin/demandes/'
      preLoaderRoute: typeof AuthenticatedAdminDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDemandesRoute
    }
    '/_authenticated/admin/demandes/$id': {
      id: '/_authenticated/admin/demandes/$id'
      path: '/$id'
      fullPath: '/admin/demandes/$id'
      preLoaderRoute: typeof AuthenticatedAdminDemandesIdRouteImport
      parentRoute: typeof AuthenticatedAdminDemandesRoute
    }
  }
}

interface AuthenticatedAdminDemandesRouteChildren {
  AuthenticatedAdminDemandesIdRoute: typeof AuthenticatedAdminDemandesIdRoute
  AuthenticatedAdminDemandesIndexRoute: typeof AuthenticatedAdminDemandesIndexRoute
}

const AuthenticatedAdminDemandesRouteChildren: AuthenticatedAdminDemandesRouteChildren =
  {
    AuthenticatedAdminDemandesIdRoute: AuthenticatedAdminDemandesIdRoute,
    AuthenticatedAdminDemandesIndexRoute: AuthenticatedAdminDemandesIndexRoute,
  }

const AuthenticatedAdminDemandesRouteWithChildren =
  AuthenticatedAdminDemandesRoute._addFileChildren(
    AuthenticatedAdminDemandesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDemandesRoute: typeof AuthenticatedAdminDemandesRouteWithChildren
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminDemandesRoute: AuthenticatedAdminDemandesRouteWithChildren,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
